### PR TITLE
expose the cli command for other libs to use

### PR DESCRIPTION
**Pull request by philschatz**
I cargo-culted this from [pumazi/cnx-db/setup.py](https://github.com/pumazi/cnx-db/blob/master/setup.py#L53-L56) but have not tested it yet. Thanks!

### CODE REVIEW

**Comment by pumazi** [comment]
Looks like you need to add `pytidylib` to the `install_requires` list. But otherwise, the script installs as expected.

**Comment by karenc** [comment]
Adding `pytidylib` and `apt-get install libtidy-dev` worked for me

But it seems the script is probably out of date:

```console
karen@yachiyo:~/src/rhaptos.cnxmlutils$ ./bin/cnxml2html -m m47526_1.2.cnxml m47526_1.2.html
pkg: rhaptos.cnxmlutils.cnxml2html
filename: cnxml2xhtml.xsl
Traceback (most recent call last):
  File "./bin/cnxml2html", line 9, in <module>
    load_entry_point('rhaptos.cnxmlutils==1.2', 'console_scripts', 'cnxml2html')()
  File "/home/karen/src/rhaptos.cnxmlutils/rhaptos/cnxmlutils/xml2xhtml.py", line 103, in main
    html = transform_cnxml(args.module)
  File "/home/karen/src/rhaptos.cnxmlutils/rhaptos/cnxmlutils/xml2xhtml.py", line 52, in transform_cnxml
    xslt = makeXsl('cnxml2xhtml.xsl')
  File "/home/karen/src/rhaptos.cnxmlutils/rhaptos/cnxmlutils/xml2xhtml.py", line 35, in makeXsl
    path = pkg_resources.resource_filename(pkg, filename)
  File "/home/karen/src/rhaptos.cnxmlutils/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1160, in resource_filename
    return get_provider(package_or_requirement).get_resource_filename(
  File "/home/karen/src/rhaptos.cnxmlutils/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 435, in get_provider
    __import__(moduleOrReq)
ImportError: No module named cnxml2html
```

**Comment by philschatz** [comment]
Thanks, added! Is there a quick/easy way to have Travis verify that the cli runs? maybe adding `cnxml2html --help` to the `script:` area in `/.travis.yml`?

**Comment by pumazi** [comment]
How about a test on the cli tool itself? See https://github.com/Connexions/cnx-archive/blob/master/cnxarchive/tests/scripts/test_hit_counter.py for an example of the `hit_counter` tool in cnx-archive.

**Comment by karenc** [comment]
I think this is probably right:

```diff
diff --git a/rhaptos/cnxmlutils/xml2xhtml.py b/rhaptos/cnxmlutils/xml2xhtml.py
index fea22a3..4bbb01e 100644
--- a/rhaptos/cnxmlutils/xml2xhtml.py
+++ b/rhaptos/cnxmlutils/xml2xhtml.py
@@ -26,7 +26,7 @@ dirname = os.path.dirname(__file__)
 
 def makeXsl(filename):
   """ Helper that creates a XSLT stylesheet """
-  pkg = 'cnxml2html'
+  pkg = 'xsl'
   package = ''.join(['.' + x for x in __name__.split('.')[:-1]])[1:]
   if package != '':
       pkg = package + '.' + pkg
@@ -39,7 +39,7 @@ def transform_collxml(collxml_file):
         (including "include" anchor links to the modules) """
 
     xml = etree.parse(collxml_file)
-    xslt = makeXsl('collxml2xhtml.xsl')
+    xslt = makeXsl('collxml-to-html5.xsl')
     xml = xslt(xml)
     return xml
 
@@ -47,7 +47,7 @@ def transform_cnxml(cnxml_file):
     """ Given a module cnxml file (index.cnxml) this returns an HTML version of it """
 
     xml = etree.parse(cnxml_file)
-    xslt = makeXsl('cnxml2xhtml.xsl')
+    xslt = makeXsl('cnxml-to-html5.xsl')
     xml = xslt(xml)
     return xml
 
```

**Comment by philschatz** [comment]
@pumazi : It seems like that does not test the code in this PR though; It seems the code in that link checks that the python file works, not that the script `cnxml2html` is provided by installing this package. But I am probably misunderstanding the link you sent 😄 

@karenc : What is that diff referring to? Are you suggesting we change which `.xsl` files are used in the `xml2html.py` file? If so, feel free to push to this PR; I'm already scared of writing code that I haven't tested yet 😄

**Comment by karenc** [comment]
@philschatz: the .xsl files referred to in the `xml2html.py` no longer exists.  The changes are my closest guess at what it is with the current state of the code.

**Comment by reedstrm** [comment]
ISTR the real problem with exposing this is that I'm not quite sure that it's the same conversion we get _in situ_ when run from the DB trigger: there's python code that also does link fixup. I'll have to review both paths. Assigning to me. :-)

**Comment by brittweinstein** [comment]
CLOSING. If this presents itself as an issue again, we will reopen.

**Pull request closed without merging**
